config/routes.rb
Rails.application.routes.draw do
  root 'tickets#index'
  resources :tickets
  resources :pages, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excavator.rb
# frozen_string_literal: true

class Excavator < ApplicationRecord
  belongs_to :ticket, inverse_of: :excavator

  validates :company_name,
            :address,
            :crew_on_site,
            presence: true
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
  has_one :excavator, inverse_of: :ticket, dependent: :restrict_with_error
  validates :request_number,
            :sequence_number,
            :request_type,
            :primary_service_area_code,
            :additional_service_area_codes,
            :response_due_date_time,
            :well_known_text,
            presence: true

  validates :request_number, uniqueness: true

  def to_param
    request_number
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def show; end
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

class TicketsController < ApplicationController
  skip_forgery_protection

  def index
    @tickets = Ticket.includes(:excavator)
                     .references(:excavator)
                     .page(params[:page] || 1)
                     .per(params[:per] || 20)
  end

  def show
    @ticket = Ticket.includes(:excavator)
                    .references(:excavator)
                    .find_by!(request_number: params[:id])
  end

  def create
    ticket = TicketService.create(params)
    if ticket.persisted?
      render json: { success: true }, status: :created
    else
      render json: {
        success: false, errors: ticket.errors.full_messages
      }, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
    <header>
      <nav>
        <div class="nav-wrapper">
          <div class="container">
            <a href="/" class="brand-logo">Caterpillar 🐛</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
              <li><%= link_to('Tickets', tickets_path) %></li>
              <li><%= link_to('API Doc', page_path(:'how-to-add-ticket')) %></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Footer Content</h5>
            <p class="grey-text text-lighten-4">
              You can use rows and columns here to organize your footer content.
            </p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Links</h5>
            <ul>
              <li>
                <%= link_to('Tickets', tickets_path, class: 'grey-text text-lighten-3') %>
              </li>
              <li>
                <%= link_to('API Doc',
                      page_path(:'how-to-add-ticket'),
                      class: 'grey-text text-lighten-3') %>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
          © <%= Time.now.strftime('%Y') %> Copyright Text
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/pages/show.html.erb
<h1>Create Ticket</h1>

<blockquote>
  To create sample ticket use this curl snippet
</blockquote>
<code>
  <pre>
      curl --location --request POST 'localhost:3000/tickets' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "RequestNumber": "09252012-00001",
          "SequenceNumber": "2421",
          "RequestType": "Normal",
          "DateTimes": {
            "ResponseDueDateTime": "2011/07/13 23:59:59"
          },
          "ServiceArea": {
            "PrimaryServiceAreaCode": {
              "SACode": "ZZGL103"
            },
            "AdditionalServiceAreaCodes": {
              "SACode": [
                "ZZL01",
                "ZZL02",
                "ZZL03"
              ]
            }
          },
          "Excavator": {
            "CompanyName": "John Doe CONSTRUCTION",
            "Address": "555 Some RD",
            "City": "SOME PARK",
            "State": "ZZ",
            "Zip": "55555",
            "CrewOnsite": "true"
          },
          "ExcavationInfo": {
            "DigsiteInfo": {
              "WellKnownText": "POLYGON((35.1648275 23.4225383,35.7821707 23.5915249,35.3173663 26.3839467,34.7867392 26.3399715,34.8318411 24.8620456,35.1738083 23.4266181))"
            }
          }
        }'
  </pre>
</code>

app/views/tickets/_ticket.html.erb
<% TicketPresenter.represent(ticket) do |presenter| %>
  <tr>
    <td nowrap>
      <%= link_to(presenter.request_number, presenter) %>
    </td>
    <td><%= presenter.sequence_number %></td>
    <td><%= presenter.due_date %></td>
    <td>
      <%= presenter.excavator.company_name %>
      <br />
      <%= presenter.excavator.address %>
    </td>
  </tr>
<% end %>

app/views/tickets/index.html.erb
<h1>Tickets</h1>

<table>
  <thead>
    <tr>
        <th>Request</th>
        <th>Sequence</th>
        <th>Due Date</th>
        <th>Excavator</th>
    </tr>
  </thead>

  <tbody>
    <% if @tickets.any? %>
      <%= render(@tickets) %>
    <% else %>
      <tr>
        <td colspan=4>
          no tickets so far.
          <%= link_to('how to create', page_path(:'how-to-add-ticket')) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/show.html.erb
<% TicketPresenter.represent(@ticket, i18n_datetime_format: :long) do |ticket| %>
  <h1>Ticket #<%= ticket.request_number %></h1>
  <h2><%= l(ticket.created_at, format: :long) %></h2>
  <div class="row">
    <div class="col s12">
      <div class="card">
        <div class="card-content white-text">
          <div id="map" style="height: 500px; width: 100%;"></div>
        </div>
        <div class="card-content">
          <div class="row">
            <div class="col s6">
              <p><b>Details</b></p>
              <p>
                Sequence Number: <%= ticket.sequence_number %>
              </p>
              <p>
                Request Type: <%= ticket.request_type %>
              </p>
              <p>
                Due Date: <%= ticket.due_date %>
              </p>
              <p>
                Area Code: <%= ticket.primary_service_area_code %>
              </p>
              <p>
                Additional Area Codes: <%= ticket.additional_area_codes %>
              </p>
            </div>
            <% if ticket.excavator %>
              <% ExcavatorPresenter.represent(ticket.excavator) do |excavator| %>
                <div class="col s6">
                  <p><b>Excavator</b></p>
                  <p><%= excavator.company_name %></p>
                  <p><%= excavator.address %></p>
                  <p><%= excavator.crew_on_site %></p>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
    function initMap() {

      const map = new google.maps.Map(document.getElementById("map"), {
        zoom: 6,
        center: <%= ticket.polygon_coords.first.to_json.html_safe %>
      });

      const polygon_coords = <%= ticket.polygon_coords.to_json.html_safe %>;
      const polygon = new google.maps.Polygon({
        paths: polygon_coords,
        strokeColor: "#FF0000",
        strokeOpacity: 0.8,
        strokeWeight: 2,
        fillColor: "#FF0000",
        fillOpacity: 0.1,
      });
      polygon.setMap(map);
    }
  </script>

  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQEBViOZmvou-ECtwgJcZ2Q61to91ZAew&callback=initMap&libraries=&v=weekly"
    async
  ></script>
<% end %>